Repository dc-github-mgall/gm-benchmark, pull requests merged in 2020-03, with the labels that each got.

#2 Add node.js implementation
  brainfuck/bench.yml
  brainfuck/node/bf.js
  runner/src/main.rs
Labels: enhancement

#5 Fix issue #3
  brainfuck/python/bf.py
Labels: bug

#6 Support multiple implmentations
  brainfuck/bench.yml
  brainfuck/js/bf.js
  runner/src/main.rs
Labels: enhancement

#7 Add C++
  .gitignore
  brainfuck/bench.yml
  brainfuck/cpp/bf.cc
  brainfuck/python/bf.py
  runner/src/main.rs
Labels: enhancement

#8 Better error handle message
  runner/src/main.rs
Labels: enhancement

#14 Unwrap source folder
  .gitignore
  bench.sh
  brainfuck/bench.yml
  brainfuck/bf.cc
  brainfuck/bf.js
  brainfuck/bf.py
  brainfuck/bf.rs
  brainfuck/rust/bf-idiomatic/Cargo.lock
  brainfuck/rust/bf-idiomatic/Cargo.toml
  runner/Cargo.lock
  runner/Cargo.toml
  runner/src/main.rs
Labels: Runner, T-Enhancement

#15 Add clang
  brainfuck/bench.yml
  runner/src/main.rs
Labels: L-C++, Runner

#16 Support customize bench-count
  bench.sh
  runner/src/main.rs
Labels: Runner, T-Enhancement
